# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

Layout/LineLength:
  Max: 120
Layout/EndOfLine:
    EnforcedStyle: lf
Style/AutoResourceCleanup:
      Enabled: true
Style/SymbolArray:
  EnforcedStyle: brackets
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: diff_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: diff_comma

Style/HashSyntax:
  EnforcedShorthandSyntax: always